[package]
name = "execute"
version = "0.1.0"
edition = "2021"

[dependencies]
factory = { path = "../factory" }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }

[[bin]]
name = "execute"
path = "src/main.rs"